from functools import cache
import numpy as np

from .dtypes import Field, build_dtype, filter_fields_by_version

event_header_fields = [
    Field(1, "event_header", dtype="S4", min_version=np.float32(6.5)),
    Field(2, "event_number", min_version=np.float32(6.5)),
    Field(3, "particle_id", min_version=np.float32(6.5)),
    Field(4, "total_energy", unit="GeV", min_version=np.float32(6.5)),
    Field(5, "starting_altitude", unit="g/cm2", min_version=np.float32(6.5)),
    Field(6, "first_target_id", min_version=np.float32(6.5)),
    Field(7, "first_interaction_height", unit="cm", min_version=np.float32(6.5)),
    Field(8, "momentum_x", unit="GeV/c", min_version=np.float32(6.5)),
    Field(9, "momentum_y", unit="GeV/c", min_version=np.float32(6.5)),
    Field(10, "momentum_minus_z", unit="GeV/c", min_version=np.float32(6.5)),
    Field(11, "zenith", unit="rad", min_version=np.float32(6.5)),
    Field(12, "azimuth", unit="rad", min_version=np.float32(6.5)),
    Field(13, "n_random_sequences", min_version=np.float32(6.5)),
    Field(13 + 1, "random_seeds", shape=(10, 3), min_version=np.float32(6.5)),
    Field(44, "run_number", min_version=np.float32(6.5)),
    Field(45, "date", min_version=np.float32(6.5)),
    Field(46, "version", min_version=np.float32(6.5)),
    Field(47, "n_observation_levels", min_version=np.float32(6.5)),
    Field(47 + 1, "observation_height", unit="cm", shape=10, min_version=np.float32(6.5)),
    Field(58, "energy_spectrum_slope", min_version=np.float32(6.5)),
    Field(59, "energy_min", unit="GeV", min_version=np.float32(6.5)),
    Field(60, "energy_max", unit="GeV", min_version=np.float32(6.5)),
    Field(61, "energy_cutoff_hadrons", unit="GeV", min_version=np.float32(6.5)),
    Field(62, "energy_cutoff_muons", unit="GeV", min_version=np.float32(6.5)),
    Field(63, "energy_cutoff_electrons", unit="GeV", min_version=np.float32(6.5)),
    Field(64, "energy_cutoff_photons", unit="GeV", min_version=np.float32(6.5)),
    Field(65, "nflain", min_version=np.float32(6.5)),
    Field(66, "nfdif", min_version=np.float32(6.5)),
    Field(67, "nflpi0", min_version=np.float32(6.5)),
    Field(68, "nflpif", min_version=np.float32(6.5)),
    Field(69, "nflche", min_version=np.float32(6.5)),
    Field(70, "nfragm", min_version=np.float32(6.5)),
    Field(71, "earth_magnetic_field_x", unit="uT", min_version=np.float32(6.5)),
    Field(72, "earth_magnetic_field_z", unit="uT", min_version=np.float32(6.5)),
    Field(73, "egs4_flag", min_version=np.float32(6.5)),
    Field(74, "nkg_flag", min_version=np.float32(6.5)),
    Field(75, "low_energy_hadron_model", min_version=np.float32(6.5)),
    Field(76, "high_energy_hadron_model", min_version=np.float32(6.5)),
    Field(77, "cerenkov_flag", min_version=np.float32(6.5)),
    Field(78, "neutrino_flag", min_version=np.float32(6.5)),
    Field(79, "curved_flag", min_version=np.float32(6.5)),
    Field(80, "computer", min_version=np.float32(6.5)),
    Field(81, "theta_min", unit="deg", min_version=np.float32(6.5)),
    Field(82, "theta_max", unit="deg", min_version=np.float32(6.5)),
    Field(83, "phi_min", unit="deg", min_version=np.float32(6.5)),
    Field(84, "phi_max", unit="deg", min_version=np.float32(6.5)),
    Field(85, "cherenkov_bunch_size", min_version=np.float32(6.5)),
    Field(86, "n_cherenkov_detectors_x", min_version=np.float32(6.5)),
    Field(87, "n_cherenkov_detectors_y", min_version=np.float32(6.5)),
    Field(88, "cherenkov_detector_grid_spacing_x", unit="cm", min_version=np.float32(6.5)),
    Field(89, "cherenkov_detector_grid_spacing_y", unit="cm", min_version=np.float32(6.5)),
    Field(90, "cherenkov_detector_length_x", unit="cm", min_version=np.float32(6.5)),
    Field(91, "cherenkov_detector_length_y", unit="cm", min_version=np.float32(6.5)),
    Field(92, "cherenkov_output_flag", min_version=np.float32(6.5)),
    Field(93, "angle_array_x_magnetic_north", unit="rad", min_version=np.float32(6.5)),
    Field(94, "additional_muon_information_flag", min_version=np.float32(6.5)),
    Field(95, "egs4_multpliple_scattering_step_length_factor", min_version=np.float32(6.5)),
    Field(96, "cherenkov_wavelength_min", unit="nm", min_version=np.float32(6.5)),
    Field(97, "cherenkov_wavelength_max", unit="nm", min_version=np.float32(6.5)),
    Field(98, "n_reuse", min_version=np.float32(6.5)),
    Field(98 + 1, "reuse_x", shape=20, min_version=np.float32(6.5)),
    Field(118 + 1, "reuse_y", shape=20, min_version=np.float32(6.5)),
    Field(139, "sybill_interaction_flag", min_version=np.float32(6.5)),
    Field(140, "sybill_cross_section_flag", min_version=np.float32(6.5)),
    Field(141, "qgsjet_interaction_flag", min_version=np.float32(6.5)),
    Field(142, "qgsjet_cross_section_flag", min_version=np.float32(6.5)),
    Field(143, "dpmjet_interaction_flag", min_version=np.float32(6.5)),
    Field(144, "dpmjet_cross_section_flag", min_version=np.float32(6.5)),
    Field(145, "venus_nexus_epos_cross_section_flag", min_version=np.float32(6.5)),
    Field(146, "muon_multiple_scattering_flag", min_version=np.float32(6.5)),
    Field(147, "nkg_radial_distribution_range", unit="cm", min_version=np.float32(6.5)),
    Field(148, "energy_fraction_if_thinning_level_hadronic", min_version=np.float32(6.5)),
    Field(149, "energy_fraction_if_thinning_level_em", min_version=np.float32(6.5)),
    Field(150, "actual_weight_limit_thinning_hadronic", min_version=np.float32(6.5)),
    Field(151, "actual_weight_limit_thinning_em", min_version=np.float32(6.5)),
    Field(152, "max_radius_radial_thinning_cutting", unit="cm", min_version=np.float32(6.5)),
    Field(153, "viewcone_inner_angle", unit="deg", min_version=np.float32(6.5)),
    Field(154, "viewcone_outer_angle", unit="deg", min_version=np.float32(6.5)),
    Field(155, "transition_energy_low_high_energy_model", unit="GeV", min_version=np.float32(6.5)),
    Field(156, "skimming_incidence_flag", min_version=np.float32(7.3)),
    Field(157, "horizontal_shower_exis_altitude", unit="cm", min_version=np.float32(7.3)),
    Field(158, "starting_height", unit="cm", min_version=np.float32(7.3)),
    Field(159, "explicit_charm_generation_flag", min_version=np.float32(7.3)),
    Field(
        160, "electromagnetic_subshower_hadronic_origin_output_flag", min_version=np.float32(7.3)
    ),
    Field(161, "conex_min_vertical_depth", unit="g/cm2", min_version=np.float32(7.3)),
    Field(162, "conex_high_energy_treshold_hadrons", unit="GeV", min_version=np.float32(7.3)),
    Field(163, "conex_high_energy_treshold_muons", unit="GeV", min_version=np.float32(7.3)),
    Field(164, "conex_high_energy_treshold_em", unit="GeV", min_version=np.float32(7.3)),
    Field(165, "conex_low_energy_treshold_hadrons", unit="GeV", min_version=np.float32(7.3)),
    Field(166, "conex_low_energy_treshold_muons", unit="GeV", min_version=np.float32(7.3)),
    Field(167, "conex_low_energy_treshold_em", unit="GeV", min_version=np.float32(7.3)),
    Field(168, "observaton_level_curvature_flag", min_version=np.float32(7.3)),
    Field(169, "conex_weight_limit_thinning_hadronic", min_version=np.float32(7.3)),
    Field(170, "conex_weight_limit_thinning_em", min_version=np.float32(7.3)),
    Field(171, "conex_weight_limit_sampling_hadronic", min_version=np.float32(7.3)),
    Field(172, "conex_weight_limit_sampling_muons", min_version=np.float32(7.3)),
    Field(173, "conex_weight_limit_sampling_em", min_version=np.float32(7.3)),
    Field(174, "augerhit_stripes_half_width", unit="cm", min_version=np.float32(7.5)),
    Field(175, "augerhit_detector_distance", unit="cm", min_version=np.float32(7.5)),
    Field(176, "augerhit_reserved", min_version=np.float32(7.5)),
    Field(177, "n_multithin", min_version=np.float32(7.5)),
    Field(177 + 1, "multithin_energy_fraction_hadronic", shape=6, min_version=np.float32(7.5)),
    Field(183 + 1, "multithin_weight_limit_hadronic", shape=6, min_version=np.float32(7.5)),
    Field(189 + 1, "multithin_energy_fraction_em", shape=6, min_version=np.float32(7.5)),
    Field(195 + 1, "multithin_weight_limit_em", shape=6, min_version=np.float32(7.5)),
    Field(199 + 3, "multithin_random_seeds", shape=(6, 3), min_version=np.float32(7.5)),
    Field(220, "icecube_energy_threshold", unit="GeV", min_version=np.float32(7.5)),
    Field(221, "icecube_gzip_flag", min_version=np.float32(7.5)),
    Field(222, "icecube_pipe_flag", min_version=np.float32(7.5)),
    Field(223, "coast_multi_thin_index", min_version=np.float32(7.74)),
    Field(224, "coast_multi_thin_flag", min_version=np.float32(7.74)),
    Field(225, "inclined_observation_plane_x", unit="cm", min_version=np.float32(7.75)),
    Field(226, "inclined_observation_plane_y", unit="cm", min_version=np.float32(7.75)),
    Field(227, "inclined_observation_plane_z", unit="cm", min_version=np.float32(7.75)),
    Field(228, "inclined_observation_plane_theta", unit="rad", min_version=np.float32(7.75)),
    Field(229, "inclined_observation_plane_phi", unit="rad", min_version=np.float32(7.75)),
    Field(230, "inclined_observation_plane_depth", min_version=np.float32(7.75)),
    Field(231, "fluka_version", min_version=np.float32(7.76)),
]


def get_event_header_fields(version):
    return filter_fields_by_version(event_header_fields, version)


@cache
def get_event_header_dtype(version):
    return build_dtype(get_event_header_fields(version))


@cache
def get_event_header_thin_dtype(version):
    return build_dtype(get_event_header_fields(version), itemsize=4 * 312)
