name: CI

# this avoids duplicated builds on pull request for the cost
on:
  push:
    branches:
      - main
    tags:
      - '**'
  pull_request:

env:
  NUMBA_NUM_THREADS: 1
  MPLBACKEND: Agg
  PYTEST_ADDOPTS: --color=yes

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13", "3.14"]

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python --version
          pip install codecov pytest-cov flake8
          pip install -e .[all]
          pip freeze

      - name: Static codechecks
        run: |
          pyflakes corsikaio

      - name: Tests
        run: |
          pytest --cov --cov-report=xml
